CREATE TABLE tracked_items (
    id BIGSERIAL PRIMARY KEY,
    url TEXT NOT NULL UNIQUE,
    name VARCHAR(255),
    target_price NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE price_logs (
    id BIGSERIAL PRIMARY KEY,
    tracked_item_id BIGINT NOT NULL REFERENCES tracked_items(id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL,
    scraped_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);